### PR TITLE
Fix #48 by wrapping html content in special div

### LINKED ISSUE #48: Building new site throws Fatal Errors
I was just trying to create a new bookdown project and followed the instructions from [Getting Started](http://bookdown.io/intro/getting-started.html).

There has been no customization. The book folder is the same as Bookdown.Project.

I'm running PHP 7.0.6 on OSX.

The issue seems to be that in `IndexProcess::processHtml` when it's matching the header tags from `$domDocument` to the return value from `$page->getHeadings()` the first header element is the h3 from `navheader.html` but that is not a heading returned from `$page->getHeadings()`.

If I change the h3 in `navheader.html` to a span tag, the site compiles correctly.

This is the output I get when I run bookdown.

```
$ ./vendor/bin/bookdown book/bookdown.json
Collecting content from book/bookdown.json
  Added root page from book/bookdown.json
  Added page book/example.md
Processing content.
  Applying Bookdown\Bookdown\Process\Conversion\ConversionProcess
    No origin for book/../../index.html
    Saving target book/../../index.html
    Reading origin book/example.md
    Saving target book/../../example.html
  Applying Bookdown\Bookdown\Process\Info\CopyrightProcess
  Applying Bookdown\Bookdown\Process\Headings\HeadingsProcess
    Processing headings for book/../../index.html
    Processing headings for book/../../example.html
  Applying Bookdown\Bookdown\Process\Resource\CopyImageProcess
    Processing copy images for book/../../index.html
    Processing copy images for book/../../example.html
  Applying Bookdown\Bookdown\Process\Toc\TocProcess
    Adding TOC entries for book/../../index.html
    Skipping TOC entries for non-index book/../../example.html
  Applying Bookdown\Bookdown\Process\Rendering\RenderingProcess
    Rendering book/../../index.html
    Rendering book/../../example.html
  Applying Bookdown\Bookdown\Process\Index\IndexProcess
    Create search index for book/../../index.html
    Create search index for book/../../example.html
PHP Notice:  Undefined offset: 3 in /private/var/www/BookdownTest/_bookdown/vendor/bookdown/bookdown/src/Process/Index/IndexProcess.php on line 115
PHP Stack trace:
PHP   1. {main}() /private/var/www/BookdownTest/_bookdown/vendor/bookdown/bookdown/bin/bookdown:0
PHP   2. Bookdown\Bookdown\Command->__invoke() /private/var/www/BookdownTest/_bookdown/vendor/bookdown/bookdown/bin/bookdown:28
PHP   3. Bookdown\Bookdown\Service\Service->__invoke() /private/var/www/BookdownTest/_bookdown/vendor/bookdown/bookdown/src/Command.php:29
PHP   4. Bookdown\Bookdown\Service\Processor->__invoke() /private/var/www/BookdownTest/_bookdown/vendor/bookdown/bookdown/src/Service/Service.php:25
PHP   5. Bookdown\Bookdown\Process\Index\IndexProcess->__invoke() /private/var/www/BookdownTest/_bookdown/vendor/bookdown/bookdown/src/Service/Processor.php:27
PHP   6. Bookdown\Bookdown\Process\Index\IndexProcess->writeIndex() /private/var/www/BookdownTest/_bookdown/vendor/bookdown/bookdown/src/Process/Index/IndexProcess.php:66
PHP   7. Bookdown\Bookdown\Process\Index\IndexProcess->processHtml() /private/var/www/BookdownTest/_bookdown/vendor/bookdown/bookdown/src/Process/Index/IndexProcess.php:88

Notice: Undefined offset: 3 in /private/var/www/BookdownTest/_bookdown/vendor/bookdown/bookdown/src/Process/Index/IndexProcess.php on line 115

Call Stack:
    0.0002     357840   1. {main}() /private/var/www/BookdownTest/_bookdown/vendor/bookdown/bookdown/bin/bookdown:0
    0.0045     788704   2. Bookdown\Bookdown\Command->__invoke() /private/var/www/BookdownTest/_bookdown/vendor/bookdown/bookdown/bin/bookdown:28
    0.0047     797224   3. Bookdown\Bookdown\Service\Service->__invoke() /private/var/www/BookdownTest/_bookdown/vendor/bookdown/bookdown/src/Command.php:29
    0.0127    1565600   4. Bookdown\Bookdown\Service\Processor->__invoke() /private/var/www/BookdownTest/_bookdown/vendor/bookdown/bookdown/src/Service/Service.php:25
    0.0357    2316920   5. Bookdown\Bookdown\Process\Index\IndexProcess->__invoke() /private/var/www/BookdownTest/_bookdown/vendor/bookdown/bookdown/src/Service/Processor.php:27
    0.0358    2316968   6. Bookdown\Bookdown\Process\Index\IndexProcess->writeIndex() /private/var/www/BookdownTest/_bookdown/vendor/bookdown/bookdown/src/Process/Index/IndexProcess.php:66
    0.0359    2319528   7. Bookdown\Bookdown\Process\Index\IndexProcess->processHtml() /private/var/www/BookdownTest/_bookdown/vendor/bookdown/bookdown/src/Process/Index/IndexProcess.php:88

PHP Fatal error:  Uncaught Error: Call to a member function getHref() on null in /private/var/www/BookdownTest/_bookdown/vendor/bookdown/bookdown/src/Process/Index/IndexProcess.php:119
Stack trace:
#0 /private/var/www/BookdownTest/_bookdown/vendor/bookdown/bookdown/src/Process/Index/IndexProcess.php(88): Bookdown\Bookdown\Process\Index\IndexProcess->processHtml('<html>\n  \n<head...', Object(Bookdown\Bookdown\Content\Page))
#1 /private/var/www/BookdownTest/_bookdown/vendor/bookdown/bookdown/src/Process/Index/IndexProcess.php(66): Bookdown\Bookdown\Process\Index\IndexProcess->writeIndex(Object(Bookdown\Bookdown\Content\Page), 'book/../../inde...')
#2 /private/var/www/BookdownTest/_bookdown/vendor/bookdown/bookdown/src/Service/Processor.php(27): Bookdown\Bookdown\Process\Index\IndexProcess->__invoke(Object(Bookdown\Bookdown\Content\Page))
#3 /private/var/www/BookdownTest/_bookdown/vendor/bookdown/bookdown/src/Service/Service.php(25): Bookdown\Bookdown\Service\Processor->__invoke(Object(Bookdown\Bookdown\Content\RootPage))
#4 /pr in /private/var/www/BookdownTest/_bookdown/vendor/bookdown/bookdown/src/Process/Index/IndexProcess.php on line 119

Fatal error: Uncaught Error: Call to a member function getHref() on null in /private/var/www/BookdownTest/_bookdown/vendor/bookdown/bookdown/src/Process/Index/IndexProcess.php on line 119

Error: Call to a member function getHref() on null in /private/var/www/BookdownTest/_bookdown/vendor/bookdown/bookdown/src/Process/Index/IndexProcess.php on line 119

Call Stack:
    0.0002     357840   1. {main}() /private/var/www/BookdownTest/_bookdown/vendor/bookdown/bookdown/bin/bookdown:0
    0.0045     788704   2. Bookdown\Bookdown\Command->__invoke() /private/var/www/BookdownTest/_bookdown/vendor/bookdown/bookdown/bin/bookdown:28
    0.0047     797224   3. Bookdown\Bookdown\Service\Service->__invoke() /private/var/www/BookdownTest/_bookdown/vendor/bookdown/bookdown/src/Command.php:29
    0.0127    1565600   4. Bookdown\Bookdown\Service\Processor->__invoke() /private/var/www/BookdownTest/_bookdown/vendor/bookdown/bookdown/src/Service/Service.php:25
    0.0357    2316920   5. Bookdown\Bookdown\Process\Index\IndexProcess->__invoke() /private/var/www/BookdownTest/_bookdown/vendor/bookdown/bookdown/src/Service/Processor.php:27
    0.0358    2316968   6. Bookdown\Bookdown\Process\Index\IndexProcess->writeIndex() /private/var/www/BookdownTest/_bookdown/vendor/bookdown/bookdown/src/Process/Index/IndexProcess.php:66
    0.0359    2319528   7. Bookdown\Bookdown\Process\Index\IndexProcess->processHtml() /private/var/www/BookdownTest/_bookdown/vendor/bookdown/bookdown/src/Process/Index/IndexProcess.php:88
```

### PR DESCRIPTION
**Pull request by tobiju**

### CODE REVIEW

File: src/Process/Index/IndexProcess.php [hunk 1]
```diff
@@ -135,12 +135,16 @@ protected function processHtml($html, Page $page)
...
-            array_push($this->searchIndex, array(
-                'id' => $this->getHeadings()[$key]['href'],
-                'title' => $this->getHeadings()[$key]['title'],
-                'content' => $content
-            ));
+        $contents = $this->getContents();
+
+        if (count($contents) > 0) {
+            foreach ($contents as $key => $content) {
+                array_push($this->searchIndex, array(
```
Comment (msphn) [inline src/Process/Index/IndexProcess.php:142]: I would favor $this->searchIndex[] instead of array_push

File: src/Process/Index/IndexProcess.php [hunk 2]
```diff
@@ -153,7 +157,7 @@ protected function buildRelatedContent()
     protected function getHtmlDomBody(\DOMDocument $domDocument)
     {
         $xpath = new \DomXpath($domDocument);
-        $query = '//h1/../*|//h2/../*|//h3/../*| //h4/../*| //h5/../*| //h6/../*';
+        $query = '//div[@id="section-main"]//h1/../*|//div[@id="section-main"]//h2/../*|//div[@id="section-main"]//h3/../*|//div[@id="section-main"]//h4/../*|//div[@id="section-main"]//h5/../*|//div[@id="section-main"]//h6/../*';
```
Comment (msphn) [inline src/Process/Index/IndexProcess.php:160]: That worked for me as well

**Review by msphn — CHANGES_REQUESTED** [review]
Works for me and resolves #48

File: src/Process/Index/IndexProcess.php (hunk 1 above)
Comment (tobiju) [reply src/Process/Index/IndexProcess.php:142]: I think it is not part of that patch :).

File: src/Process/Index/IndexProcess.php (hunk 2 above)
Comment (tobiju) [reply src/Process/Index/IndexProcess.php:160]: This works for all templates now.

**Comment by sandrokeil** [comment]
Thank you guys. :+1:
